Sync employees to biometric devices
aerele/essdee_attendance pull request #2
Opened 2020-12-28 11:28 UTC by KaviyaPeriyasamy

This PR helps to achieve user management

![Screenshot from 2020-12-28 16-52-02](https://user-images.githubusercontent.com/36359901/103211158-6f9f5100-492d-11eb-9390-76fd60cde556.png)

2021-01-12 12:44 UTC, karthikeyan5 requested changes

2021-01-12 12:44 UTC, karthikeyan5 commented on essdee_attendance/essdee_attendance/doctype/essdee_attendance_settings/essdee_attendance_settings.py
> +					conn.disconnect()
refactor as discussed

2021-01-12 12:44 UTC, karthikeyan5 commented on essdee_attendance/essdee_attendance/doctype/essdee_attendance_settings/essdee_attendance_settings.py
> +		raise e
also, give provision for fingerprint enrollment.

2021-01-12 12:44 UTC, karthikeyan5 commented on essdee_attendance/essdee_attendance/doctype/essdee_attendance_settings/essdee_attendance_settings.py
> +		raise e
as discussed, I will check with the device and let you know.

2021-01-12 12:44 UTC, karthikeyan5 commented on essdee_attendance/essdee_attendance/doctype/essdee_biometric_device/essdee_biometric_device.json
> +   "reqd": 1
note to self: check if last sync works as expected.

2021-01-19 10:37 UTC, KaviyaPeriyasamy commented on essdee_attendance/essdee_attendance/doctype/essdee_attendance_settings/essdee_attendance_settings.py
> +					conn.disconnect()
Refactored here https://github.com/aerele/essdee_attendance/pull/2/commits/a994056abba2e42ca32e9d768b138c847c8c4d4e

2021-03-06 04:44 UTC, KaviyaPeriyasamy commented on essdee_attendance/essdee_attendance/doctype/essdee_attendance_settings/essdee_attendance_settings.py
> +		raise e
Checked fingerprint enrollment functionality in the device

2021-03-06 04:45 UTC, KaviyaPeriyasamy commented on essdee_attendance/essdee_attendance/doctype/essdee_biometric_device/essdee_biometric_device.json
> +   "reqd": 1
The shift-type last sync works as expected

2021-03-08 05:36 UTC, merged